version: 2
jobs:
  test:
    docker:
      # the Docker image with Cypress dependencies
      - image: circleci/python:2.7.14
    parallelism: 1
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install and login AWS configuration
          command: |
             sudo pip install awscli
             $(aws ecr get-login --no-include-email --region ap-south-1)
      - run:
          name: Install docker compose
          command: |
             curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
             chmod +x ~/docker-compose
             sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Run the test images
          command: |   
             docker run --rm  --name test -v /var/run/docker.sock:/var/run/docker.sock  -v /home/circleci/.docker/config.json:/home/circleci/.docker/config.json 271300522025.dkr.ecr.ap-south-1.amazonaws.com/colliectl:latest -i logging -s team-tiger1 -r smoke
workflows:
  version: 2
  test:
      jobs:
          - test:
              context: colliectl
