version: 2
jobs:
  test:
    docker:
      # the Docker image with Cypress dependencies
      - image: python:2.7.14
    working_directory: ~/app
    parallelism: 1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Running E2E tests with JUnit reporter
          command: |
              curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)"  -o /usr/local/bin/docker-compose
              mv /usr/local/bin/docker-compose /usr/bin/docker-compose
              chmod +x /usr/bin/docker-compose
              docker-compose run -v /root/config.json:/root/config.json colliectl:latest
              echo $value
workflows:
  version: 2
  cypress-workflow:
    jobs:
      - test:
          context: attester
